// examples/framework-integration/vue-example.vue
<script setup>
import { ref, onMounted } from 'vue';
import { DecentApp } from '../../src/client/index.js';

const ready = ref(false);
const did = ref(null);

onMounted(async () => {
  const sdk = new DecentApp({ serviceWorkerUrl: '/worker/sw.js' });
  await sdk.ready;
  ready.value = true;
  did.value = await sdk.getDID();
});
</script>

<template>
  <div>
    <div>Ready: {{ String(ready) }}</div>
    <pre>{{ JSON.stringify(did, null, 2) }}</pre>
  </div>
  
</template>

// examples/framework-integration/react-example.jsx
import { useEffect, useMemo, useState } from 'react';
import { DecentApp } from '../../src/client/index.js';

export function DecentAppDemo() {
  const sdk = useMemo(() => new DecentApp({ serviceWorkerUrl: '/worker/sw.js' }), []);
  const [ready, setReady] = useState(false);
  const [did, setDid] = useState(null);

  useEffect(() => {
    let canceled = false;
    (async () => {
      await sdk.ready; if (canceled) return; setReady(true);
      const info = await sdk.getDID(); if (!canceled) setDid(info);
    })();
    return () => { canceled = true; };
  }, [sdk]);

  return (
    <div>
      <div>Ready: {String(ready)}</div>
      <pre>{JSON.stringify(did, null, 2)}</pre>
    </div>
  );
}
